server:
  port: ${AUTH_SERVER_PORT:9000}

spring:
  datasource:
    url: ${AUTH_DB_URL:jdbc:mysql://localhost:3306/auth_db}
    username: ${AUTH_DB_USERNAME:root}
    password: ${AUTH_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}

  security:
    oauth2:
      authorizationserver:
        issuer: ${AUTH_ISSUER:http://localhost:9000}

logging:
  level:
    com.badmintonhub.authservice.config: ${AUTH_LOG_LEVEL:INFO}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
