server:
  port: ${NOTI_SERVER_PORT:8084}

spring:
  datasource:
    url: ${NOTI_DB_URL:jdbc:mysql://localhost:3306/noti_db}
    username: ${NOTI_DB_USERNAME:root}
    password: ${NOTI_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: ${KAFKA_GROUP_ID:notification-group}
      auto-offset-reset: ${KAFKA_OFFSET_RESET:earliest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: ${KAFKA_TRUSTED_PACKAGES:com.badmintonhub.notiservice.dto.event,com.badmintonhub.*}
        spring.json.use.type.headers: ${KAFKA_USE_TYPE_HEADERS:true}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}   # <- lấy từ ENV (Gmail App Password hoặc Mailtrap)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers.enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

resilience4j:
  circuitbreaker:
    instances:
      notiClient:
        registerHealthIndicator: true
        failureRateThreshold: ${CB_FAILURE_RATE:50}
        minimumNumberOfCalls: ${CB_MIN_CALLS:5}
        automaticTransitionFromOpenToHalfOpenEnabled: ${CB_AUTO_TRANSITION:true}
        waitDurationInOpenState: ${CB_OPEN_WAIT:5s}
        permittedNumberOfCallsInHalfOpenState: ${CB_HALF_OPEN_CALLS:3}
        slidingWindowSize: ${CB_WINDOW_SIZE:10}
        slidingWindowType: ${CB_WINDOW_TYPE:COUNT_BASED}
  retry:
    instances:
      notiClient:
        maxAttempts: ${RETRY_MAX_ATTEMPTS:5}
        waitDuration: ${RETRY_WAIT:2s}
