server:
  port: 8083

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://mysql:3306/order_db
    username: root
    password: 123456

  jpa:
    hibernate.ddl-auto: update
    show-sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client.serviceUrl.defaultZone: http://service-registry:8761/eureka/

management:
  tracing.sampling.probability: 1.0
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always
  prometheus.enabled: true

logging:
  level.org.springframework.web: DEBUG
  pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
