server:
  port: ${PRODUCT_SERVER_PORT:8081}

spring:
  datasource:
    url: ${PRODUCT_DB_URL:jdbc:mysql://localhost:3306/product_db}
    username: ${PRODUCT_DB_USERNAME:root}
    password: ${PRODUCT_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:true}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: ${OTEL_SAMPLING:1.0}
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_EXPOSE:*}
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS:always}

logging:
  level:
    org.springframework.web: ${WEB_LOG_LEVEL:INFO}
