server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:mysql://localhost:3306/product_db
    username: root
    password: 123456

  jpa:
    hibernate.ddl-auto: update
    show-sql: true

eureka:
  client.serviceUrl.defaultZone: http://localhost:8761/eureka/

management:
  tracing.sampling.probability: 1.0
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always

